const rules: HowToPlayRule[] = [
  {
    id: "rule-1",
    text: "The goal is to fill in the correct shape.",
    board: [
      [1, 1, 1, 1, 1],
      [1, 0, 0, 0, 1],
      [1, 1, 1, 1, 1],
      [1, 0, 0, 0, 0],
      [1, 0, 0, 0, 0],
    ],
    rowRules: [
      ["", "", "5"],
      ["", "1", "1"],
      ["", "", "5"],
      ["", "", "1"],
      ["", "", "1"],
    ],
    colRules: [
      ["5", "", ""],
      ["1", "1", ""],
      ["1", "1", ""],
      ["1", "1", ""],
      ["3", "", ""],
    ],
  },
  {
    id: "rule-2",
    text: "The number on the side is how many consecutive squares should be filled in.",
    board: [
      [1, 1, 1, 1, 1],
      [1, 0, 0, 0, 0],
      [1, 0, 0, 0, 0],
      [1, 0, 0, 0, 0],
      [1, 0, 0, 0, 0],
    ],
    rowRules: [
      ["", "", "5"],
      ["", "", ""],
      ["", "", ""],
      ["", "", ""],
      ["", "", ""],
    ],
    colRules: [
      ["5", "", ""],
      ["", "", ""],
      ["", "", ""],
      ["", "", ""],
      ["", "", ""],
    ],
  },
  {
    id: "rule-3",
    text: "The 3 on the side of the column means there are three consecutive squares to fill in.",
    board: [
      [0, 0, 1, 0, 0],
      [0, 0, 1, 0, 0],
      [0, 0, 1, 0, 0],
      [0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0],
    ],
    rowRules: [
      ["", "", "1"],
      ["", "", "1"],
      ["", "", "1"],
      ["", "", ""],
      ["", "", ""],
    ],
    colRules: [
      ["", "", ""],
      ["", "", ""],
      ["3", "", ""],
      ["", "", ""],
      ["", "", ""],
    ],
  },
  {
    id: "rule-4",
    text: "A space between two numbers means there is a space between filled squares.",
    board: [
      [0, 0, 0, 0, 0],
      [1, 1, 0, 1, 1],
      [0, 0, 0, 0, 0],
      [1, 1, 1, 0, 1],
      [0, 0, 0, 0, 0],
    ],
    rowRules: [
      ["", "", ""],
      ["", "2", "2"],
      ["", "", ""],
      ["", "3", "1"],
      ["", "", ""],
    ],
    colRules: [
      ["", "1", "1"],
      ["", "1", "1"],
      ["", "", "1"],
      ["", "", "1"],
      ["", "1", "1"],
    ],
  },
  {
    id: "rule-5",
    text: "Look at each row clue to see how many consecutive squares belong in that row.",
    board: [
      [1, 1, 1, 1, 1],
      [1, 0, 0, 0, 1],
      [1, 1, 1, 1, 1],
      [1, 0, 0, 0, 0],
      [1, 0, 0, 0, 0],
    ],
    rowRules: [
      ["", "", "5"],
      ["", "1", "1"],
      ["", "", "5"],
      ["", "", "1"],
      ["", "", "1"],
    ],
    colRules: [
      ["5", "", ""],
      ["1", "1", ""],
      ["1", "1", ""],
      ["1", "1", ""],
      ["3", "", ""],
    ],
  },
];

export { rules };
