export { default as About } from './About'
export { default as ClipboardPing } from './ClipboardPing'
export { default as Footer } from './Footer'
export { default as Game } from './Game'
export { default as GameOver } from './GameOver'
export { default as Navbar } from './Navbar'
export { default as Settings } from './Settings'
export { default as Stats } from './Stats'