export { default as HowToPlay } from './HowToPlay/HowToPlay'
export { default as Ping } from './Ping'
export { default as Footer } from './Footer'
export { default as SolveToStart } from './Game/SolveToStart'
export { default as Game } from './Game/Game'
export { default as Navbar } from './Navbar'
export { default as Settings } from './Settings'
export { default as Stats } from './Stats'